name: authentication_repository
description: An authentication repository that handles the authentication domain
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  backend_client:
    path: ../backend_client  
