name: authentication_repository
description: An authentication repository that handles the authentication domain
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  backend_client:
    path: ../backend_client  
  user_repository:
    path: ../user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  
