# Generated by Django 3.2.4 on 2021-07-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='date',
            new_name='sent_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='due_date',
        ),
    ]
