name: user_repository
description: A user repository that handles the user domain
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  backend_client:
    path: ../backend_client
  equatable: ^2.0.0

